/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the areahandled service. Represents a row in the &quot;areahandled&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.areahandledModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.areahandledImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see areahandled
 * @see userapi.model.impl.areahandledImpl
 * @see userapi.model.impl.areahandledModelImpl
 * @generated
 */
@ProviderType
public interface areahandledModel extends BaseModel<areahandled> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a areahandled model instance should use the {@link areahandled} interface instead.
	 */

	/**
	 * Returns the primary key of this areahandled.
	 *
	 * @return the primary key of this areahandled
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this areahandled.
	 *
	 * @param primaryKey the primary key of this areahandled
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the area_id of this areahandled.
	 *
	 * @return the area_id of this areahandled
	 */
	public int getArea_id();

	/**
	 * Sets the area_id of this areahandled.
	 *
	 * @param area_id the area_id of this areahandled
	 */
	public void setArea_id(int area_id);

	/**
	 * Returns the area of this areahandled.
	 *
	 * @return the area of this areahandled
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this areahandled.
	 *
	 * @param area the area of this areahandled
	 */
	public void setArea(String area);

	/**
	 * Returns the business_id of this areahandled.
	 *
	 * @return the business_id of this areahandled
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this areahandled.
	 *
	 * @param business_id the business_id of this areahandled
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this areahandled.
	 *
	 * @return the isactive of this areahandled
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this areahandled.
	 *
	 * @param isactive the isactive of this areahandled
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.areahandled areahandled);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.areahandled> toCacheModel();

	@Override
	public userapi.model.areahandled toEscapedModel();

	@Override
	public userapi.model.areahandled toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}