/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the branch service. Represents a row in the &quot;branch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.branchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.branchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see branch
 * @see userapi.model.impl.branchImpl
 * @see userapi.model.impl.branchModelImpl
 * @generated
 */
@ProviderType
public interface branchModel extends BaseModel<branch> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a branch model instance should use the {@link branch} interface instead.
	 */

	/**
	 * Returns the primary key of this branch.
	 *
	 * @return the primary key of this branch
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this branch.
	 *
	 * @param primaryKey the primary key of this branch
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the branch_id of this branch.
	 *
	 * @return the branch_id of this branch
	 */
	public int getBranch_id();

	/**
	 * Sets the branch_id of this branch.
	 *
	 * @param branch_id the branch_id of this branch
	 */
	public void setBranch_id(int branch_id);

	/**
	 * Returns the branch of this branch.
	 *
	 * @return the branch of this branch
	 */
	@AutoEscape
	public String getBranch();

	/**
	 * Sets the branch of this branch.
	 *
	 * @param branch the branch of this branch
	 */
	public void setBranch(String branch);

	/**
	 * Returns the business_id of this branch.
	 *
	 * @return the business_id of this branch
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this branch.
	 *
	 * @param business_id the business_id of this branch
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this branch.
	 *
	 * @return the isactive of this branch
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this branch.
	 *
	 * @param isactive the isactive of this branch
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.branch branch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.branch> toCacheModel();

	@Override
	public userapi.model.branch toEscapedModel();

	@Override
	public userapi.model.branch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}