/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the designation service. Represents a row in the &quot;designation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.designationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.designationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see designation
 * @see userapi.model.impl.designationImpl
 * @see userapi.model.impl.designationModelImpl
 * @generated
 */
@ProviderType
public interface designationModel extends BaseModel<designation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a designation model instance should use the {@link designation} interface instead.
	 */

	/**
	 * Returns the primary key of this designation.
	 *
	 * @return the primary key of this designation
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this designation.
	 *
	 * @param primaryKey the primary key of this designation
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the desig_id of this designation.
	 *
	 * @return the desig_id of this designation
	 */
	public int getDesig_id();

	/**
	 * Sets the desig_id of this designation.
	 *
	 * @param desig_id the desig_id of this designation
	 */
	public void setDesig_id(int desig_id);

	/**
	 * Returns the designation of this designation.
	 *
	 * @return the designation of this designation
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this designation.
	 *
	 * @param designation the designation of this designation
	 */
	public void setDesignation(String designation);

	/**
	 * Returns the business_id of this designation.
	 *
	 * @return the business_id of this designation
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this designation.
	 *
	 * @param business_id the business_id of this designation
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this designation.
	 *
	 * @return the isactive of this designation
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this designation.
	 *
	 * @param isactive the isactive of this designation
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.designation designation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.designation> toCacheModel();

	@Override
	public userapi.model.designation toEscapedModel();

	@Override
	public userapi.model.designation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}