/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the grade service. Represents a row in the &quot;grade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.gradeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.gradeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see grade
 * @see userapi.model.impl.gradeImpl
 * @see userapi.model.impl.gradeModelImpl
 * @generated
 */
@ProviderType
public interface gradeModel extends BaseModel<grade> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a grade model instance should use the {@link grade} interface instead.
	 */

	/**
	 * Returns the primary key of this grade.
	 *
	 * @return the primary key of this grade
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this grade.
	 *
	 * @param primaryKey the primary key of this grade
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the grade_id of this grade.
	 *
	 * @return the grade_id of this grade
	 */
	public int getGrade_id();

	/**
	 * Sets the grade_id of this grade.
	 *
	 * @param grade_id the grade_id of this grade
	 */
	public void setGrade_id(int grade_id);

	/**
	 * Returns the grade of this grade.
	 *
	 * @return the grade of this grade
	 */
	@AutoEscape
	public String getGrade();

	/**
	 * Sets the grade of this grade.
	 *
	 * @param grade the grade of this grade
	 */
	public void setGrade(String grade);

	/**
	 * Returns the business_id of this grade.
	 *
	 * @return the business_id of this grade
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this grade.
	 *
	 * @param business_id the business_id of this grade
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this grade.
	 *
	 * @return the isactive of this grade
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this grade.
	 *
	 * @param isactive the isactive of this grade
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.grade grade);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.grade> toCacheModel();

	@Override
	public userapi.model.grade toEscapedModel();

	@Override
	public userapi.model.grade toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}