/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the jvbranch service. Represents a row in the &quot;jvbranch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.jvbranchModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.jvbranchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jvbranch
 * @see userapi.model.impl.jvbranchImpl
 * @see userapi.model.impl.jvbranchModelImpl
 * @generated
 */
@ProviderType
public interface jvbranchModel extends BaseModel<jvbranch> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a jvbranch model instance should use the {@link jvbranch} interface instead.
	 */

	/**
	 * Returns the primary key of this jvbranch.
	 *
	 * @return the primary key of this jvbranch
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this jvbranch.
	 *
	 * @param primaryKey the primary key of this jvbranch
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the jvbranch_id of this jvbranch.
	 *
	 * @return the jvbranch_id of this jvbranch
	 */
	public int getJvbranch_id();

	/**
	 * Sets the jvbranch_id of this jvbranch.
	 *
	 * @param jvbranch_id the jvbranch_id of this jvbranch
	 */
	public void setJvbranch_id(int jvbranch_id);

	/**
	 * Returns the jvbranch of this jvbranch.
	 *
	 * @return the jvbranch of this jvbranch
	 */
	@AutoEscape
	public String getJvbranch();

	/**
	 * Sets the jvbranch of this jvbranch.
	 *
	 * @param jvbranch the jvbranch of this jvbranch
	 */
	public void setJvbranch(String jvbranch);

	/**
	 * Returns the business_id of this jvbranch.
	 *
	 * @return the business_id of this jvbranch
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this jvbranch.
	 *
	 * @param business_id the business_id of this jvbranch
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this jvbranch.
	 *
	 * @return the isactive of this jvbranch
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this jvbranch.
	 *
	 * @param isactive the isactive of this jvbranch
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.jvbranch jvbranch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.jvbranch> toCacheModel();

	@Override
	public userapi.model.jvbranch toEscapedModel();

	@Override
	public userapi.model.jvbranch toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}