/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the regiontable service. Represents a row in the &quot;regiontable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.regiontableModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.regiontableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see regiontable
 * @see userapi.model.impl.regiontableImpl
 * @see userapi.model.impl.regiontableModelImpl
 * @generated
 */
@ProviderType
public interface regiontableModel extends BaseModel<regiontable> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a regiontable model instance should use the {@link regiontable} interface instead.
	 */

	/**
	 * Returns the primary key of this regiontable.
	 *
	 * @return the primary key of this regiontable
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this regiontable.
	 *
	 * @param primaryKey the primary key of this regiontable
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the region_id of this regiontable.
	 *
	 * @return the region_id of this regiontable
	 */
	public int getRegion_id();

	/**
	 * Sets the region_id of this regiontable.
	 *
	 * @param region_id the region_id of this regiontable
	 */
	public void setRegion_id(int region_id);

	/**
	 * Returns the region of this regiontable.
	 *
	 * @return the region of this regiontable
	 */
	@AutoEscape
	public String getRegion();

	/**
	 * Sets the region of this regiontable.
	 *
	 * @param region the region of this regiontable
	 */
	public void setRegion(String region);

	/**
	 * Returns the business_id of this regiontable.
	 *
	 * @return the business_id of this regiontable
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this regiontable.
	 *
	 * @param business_id the business_id of this regiontable
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this regiontable.
	 *
	 * @return the isactive of this regiontable
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this regiontable.
	 *
	 * @param isactive the isactive of this regiontable
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.regiontable regiontable);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.regiontable> toCacheModel();

	@Override
	public userapi.model.regiontable toEscapedModel();

	@Override
	public userapi.model.regiontable toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}