/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the screennameempidmapping service. Represents a row in the &quot;screennameempidmapping&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.screennameempidmappingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.screennameempidmappingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see screennameempidmapping
 * @see userapi.model.impl.screennameempidmappingImpl
 * @see userapi.model.impl.screennameempidmappingModelImpl
 * @generated
 */
@ProviderType
public interface screennameempidmappingModel extends BaseModel<screennameempidmapping> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a screennameempidmapping model instance should use the {@link screennameempidmapping} interface instead.
	 */

	/**
	 * Returns the primary key of this screennameempidmapping.
	 *
	 * @return the primary key of this screennameempidmapping
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this screennameempidmapping.
	 *
	 * @param primaryKey the primary key of this screennameempidmapping
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the srno of this screennameempidmapping.
	 *
	 * @return the srno of this screennameempidmapping
	 */
	public int getSrno();

	/**
	 * Sets the srno of this screennameempidmapping.
	 *
	 * @param srno the srno of this screennameempidmapping
	 */
	public void setSrno(int srno);

	/**
	 * Returns the screenname of this screennameempidmapping.
	 *
	 * @return the screenname of this screennameempidmapping
	 */
	@AutoEscape
	public String getScreenname();

	/**
	 * Sets the screenname of this screennameempidmapping.
	 *
	 * @param screenname the screenname of this screennameempidmapping
	 */
	public void setScreenname(String screenname);

	/**
	 * Returns the empid of this screennameempidmapping.
	 *
	 * @return the empid of this screennameempidmapping
	 */
	@AutoEscape
	public String getEmpid();

	/**
	 * Sets the empid of this screennameempidmapping.
	 *
	 * @param empid the empid of this screennameempidmapping
	 */
	public void setEmpid(String empid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		userapi.model.screennameempidmapping screennameempidmapping);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.screennameempidmapping> toCacheModel();

	@Override
	public userapi.model.screennameempidmapping toEscapedModel();

	@Override
	public userapi.model.screennameempidmapping toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}