/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the unit service. Represents a row in the &quot;unit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.unitModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.unitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see unit
 * @see userapi.model.impl.unitImpl
 * @see userapi.model.impl.unitModelImpl
 * @generated
 */
@ProviderType
public interface unitModel extends BaseModel<unit> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a unit model instance should use the {@link unit} interface instead.
	 */

	/**
	 * Returns the primary key of this unit.
	 *
	 * @return the primary key of this unit
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this unit.
	 *
	 * @param primaryKey the primary key of this unit
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the unit_id of this unit.
	 *
	 * @return the unit_id of this unit
	 */
	public int getUnit_id();

	/**
	 * Sets the unit_id of this unit.
	 *
	 * @param unit_id the unit_id of this unit
	 */
	public void setUnit_id(int unit_id);

	/**
	 * Returns the unit of this unit.
	 *
	 * @return the unit of this unit
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this unit.
	 *
	 * @param unit the unit of this unit
	 */
	public void setUnit(String unit);

	/**
	 * Returns the short_name of this unit.
	 *
	 * @return the short_name of this unit
	 */
	@AutoEscape
	public String getShort_name();

	/**
	 * Sets the short_name of this unit.
	 *
	 * @param short_name the short_name of this unit
	 */
	public void setShort_name(String short_name);

	/**
	 * Returns the business_id of this unit.
	 *
	 * @return the business_id of this unit
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this unit.
	 *
	 * @param business_id the business_id of this unit
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this unit.
	 *
	 * @return the isactive of this unit
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this unit.
	 *
	 * @param isactive the isactive of this unit
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.unit unit);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.unit> toCacheModel();

	@Override
	public userapi.model.unit toEscapedModel();

	@Override
	public userapi.model.unit toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}