/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the zone service. Represents a row in the &quot;zone&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link userapi.model.impl.zoneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link userapi.model.impl.zoneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see zone
 * @see userapi.model.impl.zoneImpl
 * @see userapi.model.impl.zoneModelImpl
 * @generated
 */
@ProviderType
public interface zoneModel extends BaseModel<zone> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a zone model instance should use the {@link zone} interface instead.
	 */

	/**
	 * Returns the primary key of this zone.
	 *
	 * @return the primary key of this zone
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this zone.
	 *
	 * @param primaryKey the primary key of this zone
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the zone_id of this zone.
	 *
	 * @return the zone_id of this zone
	 */
	public int getZone_id();

	/**
	 * Sets the zone_id of this zone.
	 *
	 * @param zone_id the zone_id of this zone
	 */
	public void setZone_id(int zone_id);

	/**
	 * Returns the zone of this zone.
	 *
	 * @return the zone of this zone
	 */
	@AutoEscape
	public String getZone();

	/**
	 * Sets the zone of this zone.
	 *
	 * @param zone the zone of this zone
	 */
	public void setZone(String zone);

	/**
	 * Returns the business_id of this zone.
	 *
	 * @return the business_id of this zone
	 */
	public int getBusiness_id();

	/**
	 * Sets the business_id of this zone.
	 *
	 * @param business_id the business_id of this zone
	 */
	public void setBusiness_id(int business_id);

	/**
	 * Returns the isactive of this zone.
	 *
	 * @return the isactive of this zone
	 */
	public int getIsactive();

	/**
	 * Sets the isactive of this zone.
	 *
	 * @param isactive the isactive of this zone
	 */
	public void setIsactive(int isactive);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(userapi.model.zone zone);

	@Override
	public int hashCode();

	@Override
	public CacheModel<userapi.model.zone> toCacheModel();

	@Override
	public userapi.model.zone toEscapedModel();

	@Override
	public userapi.model.zone toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}