/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.areahandled;
import userapi.model.areahandledModel;
import userapi.model.areahandledSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the areahandled service. Represents a row in the &quot;areahandled&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link areahandledModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link areahandledImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see areahandledImpl
 * @see areahandled
 * @see areahandledModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class areahandledModelImpl extends BaseModelImpl<areahandled>
	implements areahandledModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a areahandled model instance should use the {@link areahandled} interface instead.
	 */
	public static final String TABLE_NAME = "areahandled";
	public static final Object[][] TABLE_COLUMNS = {
			{ "area_id", Types.INTEGER },
			{ "area", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("area_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("area", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table areahandled (area_id INTEGER not null primary key,area VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table areahandled";
	public static final String ORDER_BY_JPQL = " ORDER BY areahandled.area_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY areahandled.area_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.areahandled"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.areahandled"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static areahandled toModel(areahandledSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		areahandled model = new areahandledImpl();

		model.setArea_id(soapModel.getArea_id());
		model.setArea(soapModel.getArea());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<areahandled> toModels(areahandledSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<areahandled> models = new ArrayList<areahandled>(soapModels.length);

		for (areahandledSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.areahandled"));

	public areahandledModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _area_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setArea_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _area_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return areahandled.class;
	}

	@Override
	public String getModelClassName() {
		return areahandled.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("area_id", getArea_id());
		attributes.put("area", getArea());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer area_id = (Integer)attributes.get("area_id");

		if (area_id != null) {
			setArea_id(area_id);
		}

		String area = (String)attributes.get("area");

		if (area != null) {
			setArea(area);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getArea_id() {
		return _area_id;
	}

	@Override
	public void setArea_id(int area_id) {
		_area_id = area_id;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return StringPool.BLANK;
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		_area = area;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public areahandled toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (areahandled)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		areahandledImpl areahandledImpl = new areahandledImpl();

		areahandledImpl.setArea_id(getArea_id());
		areahandledImpl.setArea(getArea());
		areahandledImpl.setBusiness_id(getBusiness_id());
		areahandledImpl.setIsactive(getIsactive());

		areahandledImpl.resetOriginalValues();

		return areahandledImpl;
	}

	@Override
	public int compareTo(areahandled areahandled) {
		int primaryKey = areahandled.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof areahandled)) {
			return false;
		}

		areahandled areahandled = (areahandled)obj;

		int primaryKey = areahandled.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<areahandled> toCacheModel() {
		areahandledCacheModel areahandledCacheModel = new areahandledCacheModel();

		areahandledCacheModel.area_id = getArea_id();

		areahandledCacheModel.area = getArea();

		String area = areahandledCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			areahandledCacheModel.area = null;
		}

		areahandledCacheModel.business_id = getBusiness_id();

		areahandledCacheModel.isactive = getIsactive();

		return areahandledCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{area_id=");
		sb.append(getArea_id());
		sb.append(", area=");
		sb.append(getArea());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("userapi.model.areahandled");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>area_id</column-name><column-value><![CDATA[");
		sb.append(getArea_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>area</column-name><column-value><![CDATA[");
		sb.append(getArea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = areahandled.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			areahandled.class
		};
	private int _area_id;
	private String _area;
	private int _business_id;
	private int _isactive;
	private areahandled _escapedModel;
}