/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.functiontable;
import userapi.model.functiontableModel;
import userapi.model.functiontableSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the functiontable service. Represents a row in the &quot;functiontable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link functiontableModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link functiontableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see functiontableImpl
 * @see functiontable
 * @see functiontableModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class functiontableModelImpl extends BaseModelImpl<functiontable>
	implements functiontableModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a functiontable model instance should use the {@link functiontable} interface instead.
	 */
	public static final String TABLE_NAME = "functiontable";
	public static final Object[][] TABLE_COLUMNS = {
			{ "function_id", Types.INTEGER },
			{ "function", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("function_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("function", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table functiontable (function_id INTEGER not null primary key,function VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table functiontable";
	public static final String ORDER_BY_JPQL = " ORDER BY functiontable.function_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY functiontable.function_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.functiontable"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.functiontable"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static functiontable toModel(functiontableSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		functiontable model = new functiontableImpl();

		model.setFunction_id(soapModel.getFunction_id());
		model.setFunction(soapModel.getFunction());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<functiontable> toModels(functiontableSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<functiontable> models = new ArrayList<functiontable>(soapModels.length);

		for (functiontableSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.functiontable"));

	public functiontableModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _function_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setFunction_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _function_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return functiontable.class;
	}

	@Override
	public String getModelClassName() {
		return functiontable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("function_id", getFunction_id());
		attributes.put("function", getFunction());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer function_id = (Integer)attributes.get("function_id");

		if (function_id != null) {
			setFunction_id(function_id);
		}

		String function = (String)attributes.get("function");

		if (function != null) {
			setFunction(function);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getFunction_id() {
		return _function_id;
	}

	@Override
	public void setFunction_id(int function_id) {
		_function_id = function_id;
	}

	@JSON
	@Override
	public String getFunction() {
		if (_function == null) {
			return StringPool.BLANK;
		}
		else {
			return _function;
		}
	}

	@Override
	public void setFunction(String function) {
		_function = function;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public functiontable toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (functiontable)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		functiontableImpl functiontableImpl = new functiontableImpl();

		functiontableImpl.setFunction_id(getFunction_id());
		functiontableImpl.setFunction(getFunction());
		functiontableImpl.setBusiness_id(getBusiness_id());
		functiontableImpl.setIsactive(getIsactive());

		functiontableImpl.resetOriginalValues();

		return functiontableImpl;
	}

	@Override
	public int compareTo(functiontable functiontable) {
		int primaryKey = functiontable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof functiontable)) {
			return false;
		}

		functiontable functiontable = (functiontable)obj;

		int primaryKey = functiontable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<functiontable> toCacheModel() {
		functiontableCacheModel functiontableCacheModel = new functiontableCacheModel();

		functiontableCacheModel.function_id = getFunction_id();

		functiontableCacheModel.function = getFunction();

		String function = functiontableCacheModel.function;

		if ((function != null) && (function.length() == 0)) {
			functiontableCacheModel.function = null;
		}

		functiontableCacheModel.business_id = getBusiness_id();

		functiontableCacheModel.isactive = getIsactive();

		return functiontableCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{function_id=");
		sb.append(getFunction_id());
		sb.append(", function=");
		sb.append(getFunction());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("userapi.model.functiontable");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>function_id</column-name><column-value><![CDATA[");
		sb.append(getFunction_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>function</column-name><column-value><![CDATA[");
		sb.append(getFunction());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = functiontable.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			functiontable.class
		};
	private int _function_id;
	private String _function;
	private int _business_id;
	private int _isactive;
	private functiontable _escapedModel;
}