/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.grade;
import userapi.model.gradeModel;
import userapi.model.gradeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the grade service. Represents a row in the &quot;grade&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link gradeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link gradeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see gradeImpl
 * @see grade
 * @see gradeModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class gradeModelImpl extends BaseModelImpl<grade> implements gradeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a grade model instance should use the {@link grade} interface instead.
	 */
	public static final String TABLE_NAME = "grade";
	public static final Object[][] TABLE_COLUMNS = {
			{ "grade_id", Types.INTEGER },
			{ "grade", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("grade_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("grade", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table grade (grade_id INTEGER not null primary key,grade VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table grade";
	public static final String ORDER_BY_JPQL = " ORDER BY grade.grade_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY grade.grade_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.grade"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.grade"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static grade toModel(gradeSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		grade model = new gradeImpl();

		model.setGrade_id(soapModel.getGrade_id());
		model.setGrade(soapModel.getGrade());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<grade> toModels(gradeSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<grade> models = new ArrayList<grade>(soapModels.length);

		for (gradeSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.grade"));

	public gradeModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _grade_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setGrade_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _grade_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return grade.class;
	}

	@Override
	public String getModelClassName() {
		return grade.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("grade_id", getGrade_id());
		attributes.put("grade", getGrade());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer grade_id = (Integer)attributes.get("grade_id");

		if (grade_id != null) {
			setGrade_id(grade_id);
		}

		String grade = (String)attributes.get("grade");

		if (grade != null) {
			setGrade(grade);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getGrade_id() {
		return _grade_id;
	}

	@Override
	public void setGrade_id(int grade_id) {
		_grade_id = grade_id;
	}

	@JSON
	@Override
	public String getGrade() {
		if (_grade == null) {
			return StringPool.BLANK;
		}
		else {
			return _grade;
		}
	}

	@Override
	public void setGrade(String grade) {
		_grade = grade;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public grade toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (grade)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		gradeImpl gradeImpl = new gradeImpl();

		gradeImpl.setGrade_id(getGrade_id());
		gradeImpl.setGrade(getGrade());
		gradeImpl.setBusiness_id(getBusiness_id());
		gradeImpl.setIsactive(getIsactive());

		gradeImpl.resetOriginalValues();

		return gradeImpl;
	}

	@Override
	public int compareTo(grade grade) {
		int primaryKey = grade.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof grade)) {
			return false;
		}

		grade grade = (grade)obj;

		int primaryKey = grade.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<grade> toCacheModel() {
		gradeCacheModel gradeCacheModel = new gradeCacheModel();

		gradeCacheModel.grade_id = getGrade_id();

		gradeCacheModel.grade = getGrade();

		String grade = gradeCacheModel.grade;

		if ((grade != null) && (grade.length() == 0)) {
			gradeCacheModel.grade = null;
		}

		gradeCacheModel.business_id = getBusiness_id();

		gradeCacheModel.isactive = getIsactive();

		return gradeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{grade_id=");
		sb.append(getGrade_id());
		sb.append(", grade=");
		sb.append(getGrade());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("userapi.model.grade");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>grade_id</column-name><column-value><![CDATA[");
		sb.append(getGrade_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>grade</column-name><column-value><![CDATA[");
		sb.append(getGrade());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = grade.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			grade.class
		};
	private int _grade_id;
	private String _grade;
	private int _business_id;
	private int _isactive;
	private grade _escapedModel;
}