/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.jvbranch;
import userapi.model.jvbranchModel;
import userapi.model.jvbranchSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the jvbranch service. Represents a row in the &quot;jvbranch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link jvbranchModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link jvbranchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see jvbranchImpl
 * @see jvbranch
 * @see jvbranchModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class jvbranchModelImpl extends BaseModelImpl<jvbranch>
	implements jvbranchModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a jvbranch model instance should use the {@link jvbranch} interface instead.
	 */
	public static final String TABLE_NAME = "jvbranch";
	public static final Object[][] TABLE_COLUMNS = {
			{ "jvbranch_id", Types.INTEGER },
			{ "jvbranch", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("jvbranch_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("jvbranch", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table jvbranch (jvbranch_id INTEGER not null primary key,jvbranch VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table jvbranch";
	public static final String ORDER_BY_JPQL = " ORDER BY jvbranch.jvbranch_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY jvbranch.jvbranch_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.jvbranch"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.jvbranch"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static jvbranch toModel(jvbranchSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		jvbranch model = new jvbranchImpl();

		model.setJvbranch_id(soapModel.getJvbranch_id());
		model.setJvbranch(soapModel.getJvbranch());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<jvbranch> toModels(jvbranchSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<jvbranch> models = new ArrayList<jvbranch>(soapModels.length);

		for (jvbranchSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.jvbranch"));

	public jvbranchModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _jvbranch_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setJvbranch_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jvbranch_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return jvbranch.class;
	}

	@Override
	public String getModelClassName() {
		return jvbranch.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("jvbranch_id", getJvbranch_id());
		attributes.put("jvbranch", getJvbranch());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer jvbranch_id = (Integer)attributes.get("jvbranch_id");

		if (jvbranch_id != null) {
			setJvbranch_id(jvbranch_id);
		}

		String jvbranch = (String)attributes.get("jvbranch");

		if (jvbranch != null) {
			setJvbranch(jvbranch);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getJvbranch_id() {
		return _jvbranch_id;
	}

	@Override
	public void setJvbranch_id(int jvbranch_id) {
		_jvbranch_id = jvbranch_id;
	}

	@JSON
	@Override
	public String getJvbranch() {
		if (_jvbranch == null) {
			return StringPool.BLANK;
		}
		else {
			return _jvbranch;
		}
	}

	@Override
	public void setJvbranch(String jvbranch) {
		_jvbranch = jvbranch;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public jvbranch toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (jvbranch)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		jvbranchImpl jvbranchImpl = new jvbranchImpl();

		jvbranchImpl.setJvbranch_id(getJvbranch_id());
		jvbranchImpl.setJvbranch(getJvbranch());
		jvbranchImpl.setBusiness_id(getBusiness_id());
		jvbranchImpl.setIsactive(getIsactive());

		jvbranchImpl.resetOriginalValues();

		return jvbranchImpl;
	}

	@Override
	public int compareTo(jvbranch jvbranch) {
		int primaryKey = jvbranch.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof jvbranch)) {
			return false;
		}

		jvbranch jvbranch = (jvbranch)obj;

		int primaryKey = jvbranch.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<jvbranch> toCacheModel() {
		jvbranchCacheModel jvbranchCacheModel = new jvbranchCacheModel();

		jvbranchCacheModel.jvbranch_id = getJvbranch_id();

		jvbranchCacheModel.jvbranch = getJvbranch();

		String jvbranch = jvbranchCacheModel.jvbranch;

		if ((jvbranch != null) && (jvbranch.length() == 0)) {
			jvbranchCacheModel.jvbranch = null;
		}

		jvbranchCacheModel.business_id = getBusiness_id();

		jvbranchCacheModel.isactive = getIsactive();

		return jvbranchCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{jvbranch_id=");
		sb.append(getJvbranch_id());
		sb.append(", jvbranch=");
		sb.append(getJvbranch());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("userapi.model.jvbranch");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>jvbranch_id</column-name><column-value><![CDATA[");
		sb.append(getJvbranch_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>jvbranch</column-name><column-value><![CDATA[");
		sb.append(getJvbranch());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = jvbranch.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			jvbranch.class
		};
	private int _jvbranch_id;
	private String _jvbranch;
	private int _business_id;
	private int _isactive;
	private jvbranch _escapedModel;
}