/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.regiontable;
import userapi.model.regiontableModel;
import userapi.model.regiontableSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the regiontable service. Represents a row in the &quot;regiontable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link regiontableModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link regiontableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see regiontableImpl
 * @see regiontable
 * @see regiontableModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class regiontableModelImpl extends BaseModelImpl<regiontable>
	implements regiontableModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a regiontable model instance should use the {@link regiontable} interface instead.
	 */
	public static final String TABLE_NAME = "regiontable";
	public static final Object[][] TABLE_COLUMNS = {
			{ "region_id", Types.INTEGER },
			{ "region", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("region_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("region", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table regiontable (region_id INTEGER not null primary key,region VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table regiontable";
	public static final String ORDER_BY_JPQL = " ORDER BY regiontable.region_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY regiontable.region_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.regiontable"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.regiontable"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static regiontable toModel(regiontableSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		regiontable model = new regiontableImpl();

		model.setRegion_id(soapModel.getRegion_id());
		model.setRegion(soapModel.getRegion());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<regiontable> toModels(regiontableSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<regiontable> models = new ArrayList<regiontable>(soapModels.length);

		for (regiontableSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.regiontable"));

	public regiontableModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _region_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setRegion_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _region_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return regiontable.class;
	}

	@Override
	public String getModelClassName() {
		return regiontable.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("region_id", getRegion_id());
		attributes.put("region", getRegion());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer region_id = (Integer)attributes.get("region_id");

		if (region_id != null) {
			setRegion_id(region_id);
		}

		String region = (String)attributes.get("region");

		if (region != null) {
			setRegion(region);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getRegion_id() {
		return _region_id;
	}

	@Override
	public void setRegion_id(int region_id) {
		_region_id = region_id;
	}

	@JSON
	@Override
	public String getRegion() {
		if (_region == null) {
			return StringPool.BLANK;
		}
		else {
			return _region;
		}
	}

	@Override
	public void setRegion(String region) {
		_region = region;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public regiontable toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (regiontable)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		regiontableImpl regiontableImpl = new regiontableImpl();

		regiontableImpl.setRegion_id(getRegion_id());
		regiontableImpl.setRegion(getRegion());
		regiontableImpl.setBusiness_id(getBusiness_id());
		regiontableImpl.setIsactive(getIsactive());

		regiontableImpl.resetOriginalValues();

		return regiontableImpl;
	}

	@Override
	public int compareTo(regiontable regiontable) {
		int primaryKey = regiontable.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof regiontable)) {
			return false;
		}

		regiontable regiontable = (regiontable)obj;

		int primaryKey = regiontable.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<regiontable> toCacheModel() {
		regiontableCacheModel regiontableCacheModel = new regiontableCacheModel();

		regiontableCacheModel.region_id = getRegion_id();

		regiontableCacheModel.region = getRegion();

		String region = regiontableCacheModel.region;

		if ((region != null) && (region.length() == 0)) {
			regiontableCacheModel.region = null;
		}

		regiontableCacheModel.business_id = getBusiness_id();

		regiontableCacheModel.isactive = getIsactive();

		return regiontableCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{region_id=");
		sb.append(getRegion_id());
		sb.append(", region=");
		sb.append(getRegion());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("userapi.model.regiontable");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>region_id</column-name><column-value><![CDATA[");
		sb.append(getRegion_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>region</column-name><column-value><![CDATA[");
		sb.append(getRegion());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = regiontable.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			regiontable.class
		};
	private int _region_id;
	private String _region;
	private int _business_id;
	private int _isactive;
	private regiontable _escapedModel;
}