/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package userapi.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import userapi.model.unit;
import userapi.model.unitModel;
import userapi.model.unitSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the unit service. Represents a row in the &quot;unit&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link unitModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link unitImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see unitImpl
 * @see unit
 * @see unitModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class unitModelImpl extends BaseModelImpl<unit> implements unitModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unit model instance should use the {@link unit} interface instead.
	 */
	public static final String TABLE_NAME = "unit";
	public static final Object[][] TABLE_COLUMNS = {
			{ "unit_id", Types.INTEGER },
			{ "unit", Types.VARCHAR },
			{ "short_name", Types.VARCHAR },
			{ "business_id", Types.INTEGER },
			{ "isactive", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("unit_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("unit", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("short_name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("business_id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("isactive", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table unit (unit_id INTEGER not null primary key,unit VARCHAR(75) null,short_name VARCHAR(75) null,business_id INTEGER,isactive INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table unit";
	public static final String ORDER_BY_JPQL = " ORDER BY unit.unit_id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY unit.unit_id ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.userapi.model.unit"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(userapi.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.userapi.model.unit"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static unit toModel(unitSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		unit model = new unitImpl();

		model.setUnit_id(soapModel.getUnit_id());
		model.setUnit(soapModel.getUnit());
		model.setShort_name(soapModel.getShort_name());
		model.setBusiness_id(soapModel.getBusiness_id());
		model.setIsactive(soapModel.getIsactive());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<unit> toModels(unitSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<unit> models = new ArrayList<unit>(soapModels.length);

		for (unitSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(userapi.service.util.ServiceProps.get(
				"lock.expiration.time.userapi.model.unit"));

	public unitModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _unit_id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setUnit_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _unit_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return unit.class;
	}

	@Override
	public String getModelClassName() {
		return unit.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("unit_id", getUnit_id());
		attributes.put("unit", getUnit());
		attributes.put("short_name", getShort_name());
		attributes.put("business_id", getBusiness_id());
		attributes.put("isactive", getIsactive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Integer unit_id = (Integer)attributes.get("unit_id");

		if (unit_id != null) {
			setUnit_id(unit_id);
		}

		String unit = (String)attributes.get("unit");

		if (unit != null) {
			setUnit(unit);
		}

		String short_name = (String)attributes.get("short_name");

		if (short_name != null) {
			setShort_name(short_name);
		}

		Integer business_id = (Integer)attributes.get("business_id");

		if (business_id != null) {
			setBusiness_id(business_id);
		}

		Integer isactive = (Integer)attributes.get("isactive");

		if (isactive != null) {
			setIsactive(isactive);
		}
	}

	@JSON
	@Override
	public int getUnit_id() {
		return _unit_id;
	}

	@Override
	public void setUnit_id(int unit_id) {
		_unit_id = unit_id;
	}

	@JSON
	@Override
	public String getUnit() {
		if (_unit == null) {
			return StringPool.BLANK;
		}
		else {
			return _unit;
		}
	}

	@Override
	public void setUnit(String unit) {
		_unit = unit;
	}

	@JSON
	@Override
	public String getShort_name() {
		if (_short_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _short_name;
		}
	}

	@Override
	public void setShort_name(String short_name) {
		_short_name = short_name;
	}

	@JSON
	@Override
	public int getBusiness_id() {
		return _business_id;
	}

	@Override
	public void setBusiness_id(int business_id) {
		_business_id = business_id;
	}

	@JSON
	@Override
	public int getIsactive() {
		return _isactive;
	}

	@Override
	public void setIsactive(int isactive) {
		_isactive = isactive;
	}

	@Override
	public unit toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (unit)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		unitImpl unitImpl = new unitImpl();

		unitImpl.setUnit_id(getUnit_id());
		unitImpl.setUnit(getUnit());
		unitImpl.setShort_name(getShort_name());
		unitImpl.setBusiness_id(getBusiness_id());
		unitImpl.setIsactive(getIsactive());

		unitImpl.resetOriginalValues();

		return unitImpl;
	}

	@Override
	public int compareTo(unit unit) {
		int primaryKey = unit.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof unit)) {
			return false;
		}

		unit unit = (unit)obj;

		int primaryKey = unit.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<unit> toCacheModel() {
		unitCacheModel unitCacheModel = new unitCacheModel();

		unitCacheModel.unit_id = getUnit_id();

		unitCacheModel.unit = getUnit();

		String unit = unitCacheModel.unit;

		if ((unit != null) && (unit.length() == 0)) {
			unitCacheModel.unit = null;
		}

		unitCacheModel.short_name = getShort_name();

		String short_name = unitCacheModel.short_name;

		if ((short_name != null) && (short_name.length() == 0)) {
			unitCacheModel.short_name = null;
		}

		unitCacheModel.business_id = getBusiness_id();

		unitCacheModel.isactive = getIsactive();

		return unitCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{unit_id=");
		sb.append(getUnit_id());
		sb.append(", unit=");
		sb.append(getUnit());
		sb.append(", short_name=");
		sb.append(getShort_name());
		sb.append(", business_id=");
		sb.append(getBusiness_id());
		sb.append(", isactive=");
		sb.append(getIsactive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("userapi.model.unit");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>unit_id</column-name><column-value><![CDATA[");
		sb.append(getUnit_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>unit</column-name><column-value><![CDATA[");
		sb.append(getUnit());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>short_name</column-name><column-value><![CDATA[");
		sb.append(getShort_name());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>business_id</column-name><column-value><![CDATA[");
		sb.append(getBusiness_id());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isactive</column-name><column-value><![CDATA[");
		sb.append(getIsactive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = unit.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			unit.class
		};
	private int _unit_id;
	private String _unit;
	private String _short_name;
	private int _business_id;
	private int _isactive;
	private unit _escapedModel;
}